site_name: edfrw
site_url: https://edfrw.readthedocs.io
repo_url: https://github.com/antgon/edfrw
repo_name: GitHub
nav:
  - Home:
    - Overview: index.md
    - License: license.md
  - Usage:
    - The EDF specification: usage/specifications.md
    - Reading data: usage/reading.md
    - Writing data: usage/writing.md
  - API:
    - Headers: api/headers.md 
    - Reader: api/reader.md
    - Writer: api/writer.md
theme:
  name: readthedocs # windmill # material
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            merge_init_into_class: yes
          selection:
            docstring_style: numpy
markdown_extensions:
  - smarty
  - sane_lists
#extra_css: [extra.css]
